# Configuración de etiquetas automáticas basadas en archivos modificados

components:
  - changed-files:
      - any-glob-to-any-file: src/components/**/*

hooks:
  - changed-files:
      - any-glob-to-any-file: src/hooks/**/*

database:
  - changed-files:
      - any-glob-to-any-file:
          - src/lib/db.ts
          - src/core/**/*

ui:
  - changed-files:
      - any-glob-to-any-file:
          - src/components/ui/**/*
          - src/app/globals.css

scanner:
  - changed-files:
      - any-glob-to-any-file: src/components/BarcodeScanner.tsx

reposicion:
  - changed-files:
      - any-glob-to-any-file:
          - src/app/reposicion/**/*
          - src/components/reposicion/**/*
          - src/store/reposicion.ts

vencimiento:
  - changed-files:
      - any-glob-to-any-file:
          - src/components/vencimiento/**/*
          - src/store/vencimiento.ts

api:
  - changed-files:
      - any-glob-to-any-file:
          - src/app/api/**/*
          - src/services/**/*

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - "*.md"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - "*.json"
          - ".github/**/*"

pwa:
  - changed-files:
      - any-glob-to-any-file:
          - public/manifest.json
          - public/sw.js
          - src/app/PWAProvider.tsx
