name:  Bug Report
description: Reportar un error o comportamiento inesperado
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor llena los siguientes campos para ayudarnos a resolverlo r谩pidamente.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del bug
      description: Una descripci贸n clara y concisa del problema
      placeholder: 驴Qu茅 esperabas que sucediera y qu茅 sucedi贸 en realidad?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Pasos detallados para reproducir el comportamiento
      placeholder: |
        1. Ve a '...'
        2. Haz clic en '...'
        3. Escanea el c贸digo '...'
        4. Ver error
    validations:
      required: true

  - type: dropdown
    id: section
    attributes:
      label: Secci贸n afectada
      description: 驴En qu茅 parte de la app ocurre?
      options:
        - Reposici贸n
        - Vencimientos
        - Scanner de c贸digos
        - Lista de productos
        - Sincronizaci贸n
        - Instalaci贸n PWA
        - Otro
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      description: 驴Qu茅 tan cr铆tico es este bug?
      options:
        - Cr铆tico (bloquea funcionalidad principal)
        - Alto (funcionalidad importante afectada)
        - Medio (inconveniente pero hay workaround)
        - Bajo (cosm茅tico o menor)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Entorno
      description: Informaci贸n sobre tu dispositivo y navegador
      placeholder: |
        - Dispositivo: [ej. iPhone 14, Samsung Galaxy S23, Desktop]
        - OS: [ej. iOS 17, Android 13, Windows 11]
        - Navegador: [ej. Chrome 120, Safari 17]
        - Versi贸n de la app: [ej. 1.0.0]
        - 驴Online u offline?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: Si aplica, agrega screenshots para explicar el problema

  - type: textarea
    id: logs
    attributes:
      label: Console logs
      description: Si hay errores en la consola del navegador, p茅galos aqu铆
      render: shell

  - type: checkboxes
    id: additional
    attributes:
      label: Informaci贸n adicional
      options:
        - label: El error ocurre consistentemente
        - label: El error solo ocurre en modo offline
        - label: He limpiado el cach茅 del navegador
        - label: He verificado que no es un duplicado
